ALTER TABLE `booking` ADD CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `booking` ADD CONSTRAINT `movie_id` FOREIGN KEY (`movie_id`) REFERENCES `movie` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `movie` ADD CONSTRAINT `theater_id` FOREIGN KEY (`theater_id`) REFERENCES `theater` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `movie` ADD CONSTRAINT `timetable_id` FOREIGN KEY (`timetable_id`) REFERENCES `timetable` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;