spring:
#  h2:
#    console:
#      path: /h2
#      enabled: true
#    main:
#      allow-bean-definition-overriding: true
#
#  datasource:
#
##      url: jdbc:h2:mem:mydb
##      username: sa
##      password:
##      driver-class-name: org.h2.Driver


#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 28972a0e580a33dadd87
#            client-secret: c7f4cd29f8b74fc926fac64cdae8abd8e6170cac
#          google:
#           client-id: 547814275679-vc1qst338h3q3r81i3eqq6jg3u7665ka.apps.googleusercontent.com
#           client-secret: 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
#
#
#
#
#    user:
#      name: user
#      password: password
#
#  mvc:
#    log-request-details: 'true'

    datasource:
      username: root
      url: jdbc:mysql://localhost:3306/ritreez
      password: S0saS0sa
      jpa:
        hibernate:
          ddl-auto: update
    jpa:
      generate-ddl: 'true'
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: 'true'
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER
        jpa:
          properties:
            hibernate:
              globally_quoted_identifiers: 'true'

#flyway:
#  locations:
#  - classpath:db/migration
#  baselineOnMigrate: true
#  table: SCHEMA_HISTORY
    mail:
      properties:
        mail:
          smtp:
            starttls:
              enable: 'true'
            auth: 'true'
      host: smtp.gmail.com
      username: ridikqendro@gmail.com
      password: diveskmxeqytyoqc
      port: '587'


management:
  endpoints:
    web:
      exposure:
        include:
          - "*"


logging:
  level:
    org.springframework.web: TRACE
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: application.log
startingPto: 20


application:
  security:
    jwt:
      secret-key: cad25a4794c6ca50a56cfa3ba2c450c381561045baf6d3c1c276f3cf43744c56
      expiration: 86400000   # a minute 60000
      refresh-token:
        expiration: 604800000   # a week




